name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: npm install -g cordova
      - run: |
          mkdir -p www
          cordova platform add android
          cordova build android --debug
      - uses: actions/upload-artifact@v3
        with:
          name: Hasil-APK-Z-Learning
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
